import unittest
import Data_Scraper_Draft_2
from bs4 import BeautifulSoup
import requests

def getSoup(website):
    result = requests.get(website)
    content = result.text
    return BeautifulSoup(content,'lxml')

class TestScraper(unittest.TestCase):
    def setUp(self):
        self.soup_repulsion = getSoup('https://2e.aonprd.com/Spells.aspx?ID=254')
        self.soup_worm_sting = getSoup('https://2e.aonprd.com/Spells.aspx?ID=242') # NOTE: prints deities wrong
        self.soup_raise_dead = getSoup('https://2e.aonprd.com/Spells.aspx?ID=243')
        self.soup_dino_fort = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1099')
        self.soup_acid_splash = getSoup('https://2e.aonprd.com/Spells.aspx?ID=3')
        self.soup_quick_sort = getSoup('https://2e.aonprd.com/Spells.aspx?ID=978')
        self.soup_eat_fire = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1352')
        self.soup_chill_touch = getSoup('https://2e.aonprd.com/Spells.aspx?ID=35')
        self.soup_alarm = getSoup('https://2e.aonprd.com/Spells.aspx?ID=7')
        self.soup_bread_crumbs = getSoup('https://2e.aonprd.com/Spells.aspx?ID=876')
        self.soup_frost_ray = getSoup('https://2e.aonprd.com/Spells.aspx?ID=245')
        self.soup_know_dir = getSoup('https://2e.aonprd.com/Spells.aspx?ID=169')
        self.soup_time_sense = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1193')
        self.soup_jump = getSoup('https://2e.aonprd.com/Spells.aspx?ID=167')
        self.soup_deep_breath = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1315')
        self.soup_summon_instrument = getSoup('https://2e.aonprd.com/Spells.aspx?ID=721')
        self.soup_animate_dead = getSoup('https://2e.aonprd.com/Spells.aspx?ID=666')
        self.soup_choir = getSoup('https://2e.aonprd.com/Spells.aspx?ID=886')
        self.soup_exchange_image = getSoup('https://2e.aonprd.com/Spells.aspx?ID=549') # Requirements edge case -- it has links in description
        self.soup_feather_fall = getSoup('https://2e.aonprd.com/Spells.aspx?ID=111')
        self.soup_gravity_pull = getSoup('https://2e.aonprd.com/Spells.aspx?ID=921')
        self.soup_harm = getSoup('https://2e.aonprd.com/Spells.aspx?ID=146')
        self.soup_thunder_sphere = getSoup('https://2e.aonprd.com/Spells.aspx?ID=927')
        self.soup_lose_path = getSoup('https://2e.aonprd.com/Spells.aspx?ID=940')
        self.soup_spirit_torrent = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1267')
        self.soup_element_breath = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1420')
        self.soup_chrom_armor = getSoup('https://2e.aonprd.com/Spells.aspx?ID=881')
        self.soup_ann_wave = getSoup('https://2e.aonprd.com/Spells.aspx?ID=902')
        self.soup_rad_torrent = getSoup('https://2e.aonprd.com/Spells.aspx?ID=934')
        self.soup_daze = getSoup('https://2e.aonprd.com/Spells.aspx?ID=61')

        # trigger edge cases
        self.soup_element_counter = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1421')
        # another edge case is 'https://2e.aonprd.com/Spells.aspx?ID=997'  shift blame
        # 'https://2e.aonprd.com/Spells.aspx?ID=1319'

        # description edge case (contains bullet pts)
        self.soup_righteous_might = getSoup('https://2e.aonprd.com/Spells.aspx?ID=263') 
        self.soup_chromatic_image = getSoup('https://2e.aonprd.com/Spells.aspx?ID=882')
        self.soup_variable_gravity = getSoup('https://2e.aonprd.com/Spells.aspx?ID=1026')
        self.soup_fey_form = getSoup('https://2e.aonprd.com/Spells.aspx?ID=910')
        self.soup_gift = getSoup('https://2e.aonprd.com/Spells.aspx?ID=904')

        # cost test
        self.soup_holy_cascade = getSoup('https://2e.aonprd.com/Spells.aspx?ID=151')
        # 'https://2e.aonprd.com/Spells.aspx?ID=859'  mind games

        # it has another spell within the description -- 'https://2e.aonprd.com/Spells.aspx?ID=939' life connection
        # 'https://2e.aonprd.com/Spells.aspx?ID=1011'  -- summonors precaution

    def test_scrape_actions(self):
        # I tested for every type of spell action, as well as spells that have other spells listed in their description.
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_eat_fire),"reaction")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_feather_fall),"reaction")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_lose_path),"reaction") 

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_time_sense),"one action")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_jump),"one action")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_deep_breath),"one action")

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_choir),"one action to three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_gravity_pull),"one action to three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_harm),"one action to three actions")

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_repulsion),"two actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_frost_ray),"two actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_know_dir),"two actions")
    
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_spirit_torrent),"two actions or three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_element_breath),"two actions or three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_chrom_armor),"two actions or three actions")

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_quick_sort),"three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_summon_instrument),"three actions")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_animate_dead),"three actions")

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_raise_dead),"Cast Time: 10 minutes")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_alarm),"Cast Time: 10 minutes")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_bread_crumbs),"Cast Time: 1 minute")

        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_thunder_sphere),"two actions to 2 rounds")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_ann_wave), "two actions to 2 rounds")
        self.assertEqual(Data_Scraper_Draft_2.scrape_actions(self.soup_rad_torrent), "two actions to 2 rounds")

    def test_scrape_traits(self):
        # I tested for the following edge cases: No school of magic, one school of magic (a spell can't have multiple schools) no traits, one trait, several traits
        # I also tested every school of magic, which includes "Abjuration","Conjuration","Divination","Enchantment","Evocation","Illusion","Necromancy","Transmutation"
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_acid_splash), ['Evocation', ['Acid', 'Attack', 'Cantrip']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_alarm), ['Abjuration',[]])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_animate_dead),['Necromancy',[]])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_bread_crumbs),['Abjuration', []])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_chill_touch),['Necromancy', ['Cantrip', 'Negative']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_choir), ['Evocation', ['Sonic']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_chrom_armor), ['Abjuration', ['Light']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_chromatic_image), ['Illusion', ['Visual']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_deep_breath), ['', ['Air', 'Cantrip', 'Manipulate']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_dino_fort), ['Conjuration', ['Rare']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_know_dir), ['Divination', ['Cantrip', 'Detection']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_daze), ['Enchantment', ['Cantrip', 'Mental', 'Nonlethal']])
        self.assertEqual(Data_Scraper_Draft_2.scrape_traits(self.soup_jump), ['Transmutation', ['Move']])
    
    def test_scrape_traditions(self):
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_traditions(self.soup_worm_sting), "Arcane, Primal")
        print('WIP')
        # TODO: Implement this
    
    def test_scrape_deities(self):
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_deities(self.soup_worm_sting), "Ragadahn, Selket, Ydersius")
        print('WIP')
        # TODO: Implement this
    
    def test_scrape_cast_type(self):
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_cast_type(self.soup_worm_sting), "Somatic, Verbal")
        print('WIP')
        # TODO: Implement this
    
    def test_scrape_description(self):
        print('WIP')
        # TODO: Implement this
    
    def test_scrape_requirement(self):
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Requirements", self.soup_worm_sting), "")
        print('WIP')
        # TODO: Implement this
    
    def test_scrape_trigger(self):
        # TODO: finish test case setup
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Trigger", self.soup_worm_sting), "")
    
    def test_scrape_cost(self):
        # TODO: finish test case setup
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Cost", self.soup_worm_sting), "")
    
    def test_scrape_range(self):
        # TODO: finish test case setup
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Range", self.soup_worm_sting), "touch")
    
    def test_scrape_targets(self):
        # TODO: finish test case setup
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Targets", self.soup_worm_sting), "1 creature")
    
    def test_scrape_area(self):
        # TODO: finish test case setup
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Area", self.soup_worm_sting), "")
    
    def test_scrape_duration(self):
        # TODO: Add the expected test result to the code
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Duration", self.soup_worm_sting), "")
    
    def test_scrape_saving_throw(self):
        # TODO: add the expected test result to the code
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_acid_splash), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_alarm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_animate_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_ann_wave), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_bread_crumbs), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_chill_touch), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_choir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_chrom_armor), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_chromatic_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_daze), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_deep_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_dino_fort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_eat_fire), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_element_breath), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_element_counter), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_exchange_image), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_feather_fall), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_fey_form), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_frost_ray), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_gift), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_gravity_pull), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_harm), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_holy_cascade), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_jump), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_know_dir), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_lose_path), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_quick_sort), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_rad_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_raise_dead), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_repulsion), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_righteous_might), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_spirit_torrent), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_summon_instrument), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_thunder_sphere), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_time_sense), "")
        # self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_variable_gravity), "")
        self.assertEqual(Data_Scraper_Draft_2.scrape_other("Saving Throw", self.soup_worm_sting), "Fortitude")

if __name__ == '__main__':
    unittest.main()
